"""
SSE (Server-Sent Events) Streaming
"""
import json
from typing import AsyncGenerator, Dict, Any
import logging

logger = logging.getLogger(__name__)


def format_sse(data: Dict[str, Any], event: str = None) -> str:
    """
    Generate a SSE formatted message

    Args:
        data: 送信するデータ (辞書形式)
        event: イベント名 (オプション)
    
    Returns:
        SSE形式の文字列
    """
    msg = ""
    if event:
        msg += f"event: {event}\n"
    msg += f"data: {json.dumps(data, ensure_ascii=False)}\n\n"
    return msg


async def stream_json_events(
    generator: AsyncGenerator[Dict[str, Any], None]
) -> AsyncGenerator[str, None]:
    """
    JSONイベントをSSE形式でストリーミングします
    
    Args:
        generator: イベントを生成する非同期ジェネレーター
    
    Yields:
        SSE形式の文字列
    """
    try:
        async for event in generator: # Loop through events generated by the generator asynchronously
            event_type = event.get("type", "message")
            # yield is used to return the SSE message one by one, not all at once
            yield format_sse(event, event=event_type)
    except Exception as e:
        logger.error(f"Streaming error: {e}", exc_info=True)
        yield format_sse(
            {"type": "error", "message": str(e)},
            event="error"
        )