"""
SSE (Server-Sent Events) Streaming
"""
import json
from typing import AsyncGenerator, Dict, Any, Optional
import logging

from backend.app.middleware.request_context import get_trace_id

logger = logging.getLogger(__name__)


def format_sse(
    data: Dict[str, Any],
    event: Optional[str] = None,
    trace_id: Optional[str] = None,
) -> str:
    """
    Generate a SSE formatted message

    Args:
        data: 送信するデータ (辞書形式)
        event: イベント名 (オプション)
        trace_id: 明示的に上書きしたい場合に指定。None の場合は ContextVar から取得。
                  payload に既に trace_id がある場合は変更しない。

    Returns:
        SSE形式の文字列
    """
    # trace_id を payload に必ず埋め込む（フロントが SSE event ↔ BQ ログを突合できるように）
    resolved_trace_id = trace_id if trace_id is not None else get_trace_id()
    if resolved_trace_id and "trace_id" not in data:
        data = {**data, "trace_id": resolved_trace_id}

    msg = ""
    if event:
        msg += f"event: {event}\n"
    msg += f"data: {json.dumps(data, ensure_ascii=False)}\n\n"
    return msg


async def stream_json_events(
    generator: AsyncGenerator[Dict[str, Any], None]
) -> AsyncGenerator[str, None]:
    """
    JSONイベントをSSE形式でストリーミングします

    Args:
        generator: イベントを生成する非同期ジェネレーター

    Yields:
        SSE形式の文字列
    """
    try:
        async for event in generator: # Loop through events generated by the generator asynchronously
            event_type = event.get("type", "message")
            # yield is used to return the SSE message one by one, not all at once
            yield format_sse(event, event=event_type)
    except Exception as e:
        logger.error(f"Streaming error: {e}", exc_info=True)
        yield format_sse(
            {"type": "error", "message": str(e)},
            event="error"
        )